services:
  db:
    image: postgres:15
    container_name: mindhealth_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-MH_G6_BD}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgre}
    ports:
      - "5432:5432"
    volumes:
      - mindhealth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindhealth_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      #SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-MH_G6_BD}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgre}
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET:-LocalDevJwtSecretOnlyForDevNotForProd}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-LocalDevKey12345}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  mindhealth_pgdata: