services:
  db:
    image: postgres:15
    container_name: mindhealth_db
    restart: always
    environment:
      POSTGRES_DB: MH_G6_BD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - mindhealth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindhealth_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      #SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/MH_G6_BD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mindhealth_pgdata: